In [1]:
# Importing necessary packages.
# import os
# import zipfile as zip
import pandas as pd
import csv
import numpy as np

In [2]:
# import dask.dataframe as dd

In [3]:
# from dask.distributed import Client, progress
# client = Client(n_workers=2, threads_per_worker=2, memory_limit='8GB')
# client

### Load NBER Categories

In [4]:
# f_name = "application.tsv"
# f_name = "cpc_group.tsv"
# f_name = "cpc_subgroup.tsv"
# f_name = "cpc_subsection.tsv"
# f_name = "cpc_current.tsv"
# f_name = "mainclass.tsv"
# f_name = "mainclass_current.tsv"
# f_name = "subclass.tsv"
# f_name = "subclass_current.tsv"
f_name = "nber.tsv"
dtypes = {'category_id': np.int8, 'subcategory_id': np.int8}
nber = pd.read_csv(f_name, delimiter="\t", dtype=dtypes, quoting = csv.QUOTE_NONNUMERIC)

In [5]:
# nber has unique patent ids
nber['patent_id'].nunique()

5105937

In [6]:
nber.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5105937 entries, 0 to 5105936
Data columns (total 4 columns):
 #   Column          Dtype
---  ------          -----
 0   uuid            object
 1   patent_id       object
 2   category_id     int8
 3   subcategory_id  int8
dtypes: int8(2), object(2)
memory usage: 87.6+ MB

In [7]:
nber.dtypes

uuid              object
patent_id         object
category_id         int8
subcategory_id      int8
dtype: object

### load patent files

In [8]:
f_name = "patent.tsv"
dtypes = {'num_claims': np.int16, 'withdrawn': np.float32}
patent = pd.read_csv(f_name, delimiter="\t", dtype=dtypes, parse_dates = ['date'])

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (0,2,5) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [9]:
patent.head()

,id,type,number,country,date,abstract,title,kind,num_claims,filename,withdrawn
0,10000000,utility,10000000,US,2018-06-19,A frequency modulated (coherent) laser detecti...,Coherent LADAR using intra-pixel quadrature de...,B2,20,ipg180619.xml,NaN
1,10000001,utility,10000001,US,2018-06-19,The injection molding machine includes a fixed...,Injection molding machine and mold thickness c...,B2,12,ipg180619.xml,NaN
2,10000002,utility,10000002,US,2018-06-19,The present invention relates to: a method for...,Method for manufacturing polymer film and co-e...,B2,9,ipg180619.xml,NaN
3,10000003,utility,10000003,US,2018-06-19,The invention relates to a method for producin...,Method for producing a container from a thermo...,B2,18,ipg180619.xml,NaN
4,10000004,utility,10000004,US,2018-06-19,The present invention relates to provides a do...,"Process of obtaining a double-oriented film, c...",B2,6,ipg180619.xml,NaN

In [10]:
patent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7430873 entries, 0 to 7430872
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   id          object
 1   type        object
 2   number      object
 3   country     object
 4   date        datetime64[ns]
 5   abstract    object
 6   title       object
 7   kind        object
 8   num_claims  int16
 9   filename    object
 10  withdrawn   float32
dtypes: datetime64[ns](1), float32(1), int16(1), object(8)
memory usage: 552.8+ MB

In [11]:
patent['country'].unique()

array(['US'], dtype=object)

In [12]:
patent = patent[['id', 'type', 'date']]

In [13]:
patent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7430873 entries, 0 to 7430872
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   id      object
 1   type    object
 2   date    datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 170.1+ MB

### load citations

In [14]:
# f_name = "uspatentcitation.tsv"
# # dtypes = {'sequence': np.int16}
# # citation = pd.read_csv(f_name, delimiter="\t", dtype=dtypes)
# citation = pd.read_csv(f_name, delimiter="\t", usecols = ['patent_id','citation_id','date'], dtype=dtypes)

In [ ]:
# use sample for experiments // or using the file below for reading partial data
# .sample(frac=0.1)

In [15]:
# read partial data for speed/ prototypring 

f_name = "uspatentcitation.tsv"

# Take every N-th (in this case 10th) row
n = 5

# Count the lines or use an upper bound
num_lines = sum(1 for l in open(f_name))

# The row indices to skip - make sure 0 is not included to keep the header!
skip_idx = [x for x in range(1, num_lines) if x % n != 0]

# Read the data
citation = pd.read_csv(f_name, skiprows=skip_idx, delimiter="\t", usecols = ['patent_id','citation_id','date'], dtype=dtypes)

In [17]:
citation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22205287 entries, 0 to 22205286
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   patent_id    object
 1   citation_id  object
 2   date         object
dtypes: object(3)
memory usage: 508.2+ MB

In [18]:
citation.head()

  patent_id citation_id        date
0   8683318     6642945  2003-11-01
1   7398575     4894880  1990-01-01
2   7905900     5334216  1994-08-01
3   4494772     3743315  1973-07-01
4   9869441     7264387  2007-09-01

In [19]:
citation['year'] = citation['date'].astype(str).str[:4]

In [20]:
citation = citation.dropna(subset=['date'])

In [21]:
citation = citation.astype({'year': 'int16'})

In [22]:
citation = citation[['patent_id','citation_id','year']]

In [23]:
citation.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22205225 entries, 0 to 22205286
Data columns (total 3 columns):
 #   Column       Dtype
---  ------       -----
 0   patent_id    object
 1   citation_id  object
 2   year         int16
dtypes: int16(1), object(2)
memory usage: 550.6+ MB

In [24]:
# # f_name = "uspc.tsv"
# # f_name = "ipcr.tsv"
# # f_name = "patent.tsv"
# # f_name = "usapplicationcitation.tsv"
# f_name = "uspatentcitation.tsv"
# chunksize = 10 ** 6
# count = 1
# n_obs = 0
# for df in pd.read_csv(f_name, delimiter="\t", chunksize=chunksize, quoting=csv.QUOTE_NONNUMERIC):
#     print('processing chunk: ' + str(count))
#     n_obs += len(df)
#     count += 1
# # Print summary of data: number of observations, columns, and each variable data type
# print(n_obs)
# print(df.dtypes)

In [25]:
# Print summary of data: number of columns, observations, and each variable data type
# print(len(df))
# df.info()
# Print basic summary statistics for numerical variables
# print(df.describe(exclude=[np.number]))

In [26]:
# df.to_csv('usapplicationcitation_sample.csv', index=False)  
# df.to_csv('patent_sample.csv', index=False)
# df.to_csv('uspatentcitation_sample.csv', index=False)
# pd.read_csv('usapplicationcitation_sample.csv')
# pd.read_csv('patent_sample.csv')
# pd.read_csv('uspatentcitation_sample.csv')

In [27]:
# Print first five observations
# df.head(20)
# df.date.max()

## merge datasets

In [29]:
citation.dtypes

patent_id      object
citation_id    object
year            int16
dtype: object

In [30]:
nber.dtypes

uuid              object
patent_id         object
category_id         int8
subcategory_id      int8
dtype: object

In [31]:
patent.dtypes

id              object
type            object
date    datetime64[ns]
dtype: object

### merge with patents and keep only utility patents

In [32]:
citation = citation.merge(patent, left_on = "patent_id", right_on = "id", how = 'left')

In [33]:
citation.groupby('type').count()

,patent_id,citation_id,year,id,date
type,,,,,
design,2142474,2142474,2142474,2142474,2142474
plant,2913,2913,2913,2913,2913
reissue,92374,92374,92374,92374,92374
statutory invention registration,2961,2961,2961,2961,2961
utility,212534,212534,212534,212534,212534

# 89% of citations do not have a type..... impossible

In [34]:
citation[citation['type'].isnull()].shape[0] / citation.shape[0]

0.8895189758266354

In [35]:
citation = citation[~citation['type'].isin(['design','plant','reissue','statutory invention registration'])]

### add categories from NBER classification

In [36]:
citation = citation.merge(nber[['patent_id','subcategory_id']], on = "patent_id", how = 'left')\
        .rename(columns={"subcategory_id": "patent_subcategory_id"})

In [37]:
# 32% of patents don't have a subcategory_id 
citation[citation['patent_subcategory_id'].isnull()].shape[0] / citation.shape[0]

0.32006667032983493

In [38]:
citation = citation.merge(nber[['patent_id','subcategory_id']], left_on = "citation_id", right_on = "patent_id", \
                          how = 'left').rename(columns={"subcategory_id": "citation_subcategory_id"})

In [40]:
# 14% of patents don't have a subcategory_id 
citation[citation['citation_subcategory_id'].isnull()].shape[0] / citation.shape[0]

0.14728450790886205

### calculate directional citation flows

In [51]:
list_subcat = list(citation['patent_subcategory_id'].dropna().unique())

In [52]:
list_subcat.sort()

In [54]:
df_citation = pd.DataFrame()

for patent_subcategory_id in list_subcat:
    temp = citation[citation['patent_subcategory_id'] == patent_subcategory_id].groupby("citation_subcategory_id").count()\
        [['patent_subcategory_id']].rename(columns={"patent_subcategory_id": patent_subcategory_id})
    df_citation = df_citation.merge(temp, left_index=True, right_index=True, how = "outer")

In [55]:
df_citation.replace(np.nan,0)

,11.0,12.0,13.0,14.0,15.0,19.0,21.0,22.0,23.0,24.0,...,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0
citation_subcategory_id,,,,,,,,,,,,,,,,,,,,,
11.0,11062.0,800.0,49.0,1971.0,785.0,3295,54,127,105,22,...,678.0,12.0,804,124.0,68.0,17.0,5.0,54.0,1186,0.0
12.0,521.0,39612.0,473.0,1147.0,7763.0,16402,772,1115,2336,550,...,714.0,201.0,315,2772.0,567.0,455.0,191.0,458.0,13542,3.0
13.0,47.0,400.0,25903.0,217.0,183.0,8420,153,227,66,87,...,160.0,18.0,65,434.0,86.0,540.0,127.0,124.0,2745,0.0
14.0,1891.0,1817.0,281.0,49722.0,10626.0,15577,195,426,235,82,...,1056.0,36.0,22,377.0,21.0,36.0,11.0,42.0,1965,2.0
15.0,957.0,9876.0,472.0,7977.0,113500.0,23274,943,555,1075,176,...,863.0,1644.0,367,2461.0,264.0,106.0,281.0,508.0,23180,4.0
19.0,2915.0,17918.0,11583.0,13457.0,20800.0,418157,5782,8733,4822,2324,...,5033.0,889.0,2063,7932.0,1414.0,3296.0,1590.0,6416.0,38695,0.0
21.0,17.0,623.0,165.0,96.0,476.0,3637,682688,136469,21912,16722,...,716.0,2948.0,462,2688.0,1795.0,218.0,213.0,511.0,7330,12.0
22.0,73.0,709.0,239.0,121.0,262.0,4042,119177,511793,41555,75182,...,553.0,5939.0,425,1471.0,491.0,305.0,62.0,479.0,8098,44.0
23.0,77.0,2134.0,54.0,125.0,601.0,3500,21526,44916,162381,14129,...,80.0,4205.0,83,81.0,157.0,50.0,27.0,114.0,3927,20.0
24.0,0.0,466.0,91.0,67.0,82.0,1966,17835,77982,13227,261089,...,33.0,689.0,26,63.0,133.0,29.0,47.0,126.0,2674,7.0
25.0,3.0,44.0,36.0,39.0,43.0,391,26255,74327,5443,20100,...,65.0,2838.0,58,176.0,127.0,13.0,4.0,151.0,1372,4.0
31.0,2451.0,3491.0,329.0,36982.0,18953.0,28196,809,3795,193,301,...,4982.0,60.0,95,634.0,374.0,183.0,24.0,596.0,3279,11.0
32.0,88.0,3299.0,961.0,487.0,2516.0,18707,12561,17296,2182,727,...,817.0,579.0,3406,142.0,2661.0,206.0,1074.0,2534.0,10390,21.0
33.0,100.0,9.0,0.0,659.0,442.0,88,14,43,1,5,...,137.0,1.0,1,3.0,0.0,1.0,0.0,2.0,9,0.0
39.0,41.0,2941.0,27.0,147.0,1918.0,1684,432,1926,559,42,...,44.0,110.0,834,52.0,135.0,13.0,105.0,381.0,2022,7.0
41.0,44.0,529.0,144.0,50.0,339.0,2913,26396,8906,4044,5449,...,348.0,377.0,369,1323.0,772.0,455.0,892.0,479.0,4556,0.0
42.0,7.0,1220.0,115.0,111.0,164.0,3370,7794,3232,6430,421,...,262.0,568.0,368,70.0,301.0,321.0,117.0,201.0,4032,0.0
43.0,80.0,739.0,553.0,103.0,197.0,10908,12924,24953,2857,1854,...,491.0,656.0,218,5000.0,210.0,377.0,417.0,364.0,6011,3.0
44.0,16.0,676.0,166.0,127.0,147.0,4945,5237,10615,2623,1299,...,148.0,207.0,154,762.0,336.0,278.0,120.0,222.0,1817,0.0
45.0,76.0,1538.0,2326.0,233.0,646.0,10261,10690,15796,5140,3770,...,310.0,487.0,404,1414.0,1608.0,3578.0,551.0,531.0,9533,7.0
46.0,11.0,6630.0,91.0,332.0,590.0,15833,6863,11479,7966,20748,...,28.0,92.0,28,65.0,40.0,573.0,33.0,73.0,4584,7.0
49.0,44.0,1472.0,163.0,58.0,326.0,4967,28545,31915,12516,4547,...,1729.0,1386.0,393,961.0,854.0,963.0,173.0,506.0,5594,3.0
51.0,366.0,4033.0,1091.0,364.0,4759.0,19658,3347,8548,1659,1290,...,3570.0,1278.0,1693,3828.0,2587.0,631.0,1143.0,6782.0,19710,6.0
52.0,29.0,2471.0,337.0,102.0,532.0,8130,1645,2134,830,2061,...,336.0,748.0,414,3280.0,687.0,1459.0,1284.0,1369.0,7795,1.0
53.0,25.0,415.0,1120.0,49.0,102.0,6437,1085,11212,380,120,...,429.0,140.0,257,2092.0,1038.0,893.0,2028.0,277.0,9389,0.0
54.0,10.0,605.0,21.0,56.0,235.0,3616,15687,7452,8549,1506,...,86.0,395.0,129,67.0,84.0,223.0,40.0,141.0,3451,5.0
55.0,11.0,168.0,291.0,25.0,483.0,2823,3175,10176,229,123,...,852.0,1143.0,1170,1559.0,5046.0,290.0,848.0,1751.0,8665,0.0
59.0,125.0,1972.0,704.0,89.0,506.0,8326,10863,17265,5328,2063,...,2174.0,4211.0,1646,3710.0,4558.0,831.0,2314.0,3274.0,17229,7.0
61.0,399.0,526.0,221.0,662.0,489.0,4263,705,1282,98,40,...,84969.0,323.0,303,1195.0,884.0,858.0,110.0,3121.0,3756,0.0
62.0,7.0,165.0,13.0,10.0,2039.0,646,1927,5176,2899,486,...,635.0,136918.0,445,84.0,504.0,33.0,94.0,345.0,3824,0.0
63.0,789.0,335.0,49.0,28.0,169.0,2450,649,925,116,77,...,359.0,510.0,61866,110.0,1566.0,102.0,408.0,1955.0,5698,0.0
64.0,78.0,1175.0,363.0,213.0,624.0,4207,1352,1681,48,26,...,1097.0,219.0,79,128582.0,197.0,192.0,1393.0,146.0,4205,0.0
65.0,117.0,700.0,125.0,23.0,142.0,1592,1919,1051,215,146,...,1105.0,792.0,1508,288.0,103166.0,170.0,633.0,2697.0,13182,0.0
66.0,45.0,628.0,1042.0,49.0,107.0,4592,434,1278,121,34,...,1294.0,42.0,110,380.0,376.0,33298.0,334.0,266.0,5885,0.0
67.0,4.0,212.0,141.0,16.0,110.0,1581,381,139,47,67,...,233.0,200.0,372,4914.0,1222.0,276.0,25549.0,394.0,6060,0.0
68.0,59.0,667.0,187.0,31.0,437.0,6768,1039,1213,236,196,...,4615.0,480.0,1758,208.0,3878.0,258.0,424.0,77659.0,11490,0.0
69.0,945.0,13516.0,3888.0,1282.0,14679.0,39922,11583,16795,7241,4299,...,4632.0,5940.0,6321,6135.0,14088.0,4097.0,4196.0,12383.0,336608,4.0
70.0,0.0,0.0,0.0,0.0,0.0,1,5,5,7,1,...,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,2,0.0